### PR TITLE
Integrate NATS broker as a MQTT-broker

### PR DESCRIPTION
**Pull request by nintran52**
### What does this do?
- Change MQTT-broker from VerneMQ to NATS

### CODE REVIEW

**Comment by nintran52** [comment]
I skipped the tests because there are many changes from Mainflux that we will contribute by fix it when we have time (I created a ticket for that on Mainflux)

**Review by nnpvaan — APPROVED** [review]
LGTM

**Review by wilianto — APPROVED** [review]
just merge this bro. no way we can review 770k line changes 🤣

**Comment by wilianto** [comment]
if I could give a feedback. having 1 main branch for this kind of project is much simpler.
for staging & production env, we can play with docker image tagging. 1 tag for staging (latest) & 1 tag for production (stable).
developing code with 2 upstreams, 2 main branches & active internal development is hell complicated. 
most of our PR merge will be thousands of line of changes.

cc: @nintran52 @calvinchengx

**Pull request merged**
